allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
saveExact: true
trustLockfile: false
blockExoticSubdeps: true
overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.24.4
